# Generated by Django 4.2.13 on 2024-06-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_money', '0002_content_delete_contents_delete_review_delete_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='substance',
            field=models.CharField(max_length=1000),
        ),
    ]
