# Generated by Django 4.2.13 on 2024-06-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_money', '0003_alter_content_substance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='contents_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
