# Generated by Django 4.2.13 on 2024-06-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_money', '0004_alter_content_contents_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('substance', models.CharField(max_length=300)),
            ],
        ),
    ]
